// Copyright (c) 2022 Sri Lakshmi Kanthan P
// 
// This software is released under the MIT License.
// https://opensource.org/licenses/MIT


import installExtension, { REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS } from 'electron-devtools-installer';
import { Menu, MenuItem, app, ipcMain, nativeTheme } from 'electron';
import { menubar, Menubar } from 'menubar';
import { configure } from 'electron-settings';

import open from 'open';
import path from 'path';
import fs from 'fs';

import FileStore from './storage/FIleStore';
import * as settings from "./settings";
import * as U from './utilities/functions';
import * as C from './constants/constants';
import * as E from './constants/ipcevents';


// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).


// Main Window Preload Entry
declare const NOTE_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Main Window Load entry
declare const NOTE_WINDOW_WEBPACK_ENTRY: string;


/******************************************
 *          App startup phase             *
 *****************************************/


// stop your app launching at install
if (require('electron-squirrel-startup')) {
  app.quit();
}

// get the lock to chen single instance
if (!app.requestSingleInstanceLock()) {
  app.quit();
}

// Add app to system startup
app.setLoginItemSettings({
  openAtLogin: app.isPackaged,
  openAsHidden: true,
  path: app.getPath("exe")
});

// create necessary directories for the app
if (!fs.existsSync(C.APPLICATION_HOME)) {
  fs.mkdirSync(C.APPLICATION_HOME, { recursive: true })
}

// configure the electron-settings
configure({
  dir: C.APPLICATION_HOME,
  prettify: true,
  fileName: "settings.json"
});


/******************************************
 *          App state instance            *
 *****************************************/


// Main Window is created on mb.app.on('ready')
const mb: Menubar = menubar({
  index: NOTE_WINDOW_WEBPACK_ENTRY,
  tooltip: C.APPLICATION_NAME,
  icon: U.getApplicationIcon(),
  preloadWindow: true,
  browserWindow: {
    icon: U.getApplicationIcon(),
    frame: false,
    show: false,
    skipTaskbar: true,
    resizable: true,
    transparent: true,
    hasShadow: true,
    webPreferences: {
      preload: NOTE_WINDOW_PRELOAD_WEBPACK_ENTRY,
      devTools: !app.isPackaged
    }
  }
});


/******************************************
 *          App initialize section        *
 *****************************************/

// on app ready event
app.on('ready', async () => {
  // file store to store the note
  const fileStore = new FileStore(path.join(C.APPLICATION_HOME, ".notes"));

  // ipc event for recv
  ipcMain.on(E.RECV_IN_MAIN_CHAN, async (e, arg) => {
    await fileStore.setNote(arg);
  });

  // ipc event for send
  ipcMain.handle(E.SEND_IN_MAIN_CHAN, async () => {
    return await fileStore.getNote();
  });

  // install dev tools if not packaged
  if (!app.isPackaged) {
    try {
      await installExtension(REACT_DEVELOPER_TOOLS);
      await installExtension(REDUX_DEVTOOLS);
    } catch (e) {
      console.error('While installing ext: ', e.message);
    }
  }
});

// on Menu bar ready
mb.on('ready', async () => {
  // set the size of the QuickNote window
  mb.window.setSize(...await settings.getWindowSize(C.APPLICATION_SIZE));

  // on resized event save the size
  mb.window.on('resized', () => {
    settings.setWindowSize(mb.window.getSize() as [number, number]);
  });

  // set the context menu for the tray
  mb.tray.setContextMenu(Menu.buildFromTemplate([
    { label: 'About', click: () => open(C.APPLICATION_URL) },
    { label: 'Issue', click: () => open(C.ISSUE_RAISE_URL) },
    { type: 'separator' },
    { label: 'Quit', click: () => app.quit() }
  ]));

  // Create Non visible Menu 
  const menu = new Menu();

  // Add ESC to close the app
  menu.append(new MenuItem({
    label: 'Hide QuickNote',
    visible: false,
    accelerator: 'Esc',
    click: () => {
      mb.window.hide();
    }
  }));

  // Add for dev tools
  menu.append(new MenuItem({
    enabled: !mb.app.isPackaged,
    label: "Open Dev Tools",
    visible: false,
    accelerator: "Control+D",
    click: () => {
      mb.window.webContents.openDevTools();
    }
  }));

  // Add for Quit
  menu.append(new MenuItem({
    label: "Quit QuickNote",
    visible: false,
    accelerator: "Control+Q",
    click: () => {
      mb.app.quit();
    }
  }));

  // set the menu
  Menu.setApplicationMenu(menu);

  // on theme change
  nativeTheme.on('updated', () => {
    mb.window.setIcon(U.getApplicationIcon());
    mb.tray.setImage(U.getApplicationIcon());
  });

  // on app exit
  mb.app.on('quit', async () => mb.tray.destroy());
});
