name: Build - Linux (deb)

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build Debian package
        run: npm run make:linux

      - name: Upload Debian artifact
        uses: actions/upload-artifact@v4
        with:
          name: quicknote-deb
          path: out/make/deb/**/*.deb
          retention-days: 1
